[workspace]
authors = ["guna-sd <sdgunaseker@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/modular-community"]
name = "mlir"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2026011405,<0.27"
